server:
  port: 8066
# 文件存储的位置

web:
  #upload: D:\SpringWorkSpace\PassWord\img\
  upload: /home/passwordProject/imgs/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/password?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    #url: jdbc:mysql://124.223.200.36:3306/password?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Qaz11097969..=
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload}


